-- CREACION DE LA BASE DE DATOS
DROP DATABASE IF EXISTS TALLER;
CREATE DATABASE IF NOT EXISTS TALLER;
USE TALLER;

-- CREACION DE LA TABLA DE CLIENTES
DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(10)
);

-- CREACION DE LA TABLA DE VEHICULOS
DROP TABLE IF EXISTS VEHICULOS;
CREATE TABLE VEHICULOS(
    ID_VEHICULO INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50),
    COLOR VARCHAR(30) NOT NULL,
    ID_CLIENTE INT NOT NULL
);

-- CREACION DE LA TABLA DE REPARACIONES
DROP TABLE IF EXISTS REPARACIONES;
CREATE TABLE REPARACIONES(
    ID_REPARACION INT AUTO_INCREMENT PRIMARY KEY,
    COSTO_TOTAL FLOAT NOT NULL,
    COSTO_PENDIENTE FLOAT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_REPARACION DATE,
    CON_FACTURA BOOLEAN  NOT NULL DEFAULT FALSE,
    ID_VEHICULO INT NOT NULL
);

-- DATOS DE PRUEBA PARA CLIENTES
INSERT INTO CLIENTES (NOMBRE,TELEFONO) VALUES 
('ALFREDO JIMENEZ','775123123'),
('JOSE JIMENEZ','775123121'),
('PEDRO JIMENEZ','775123122'),
('RUBEN JIMENEZ','775123125');

-- DATOS DE PRUEBA PARA VEHICULOS
INSERT INTO VEHICULOS (MARCA,MODELO,COLOR,ID_CLIENTE) VALUES
('CHEVROLET','CRUIZE','ROJO',1),
('CHEVROLET','AVEO','PLATA',2),
('NISSAN','ESTAQUITAS','BLANCA',3),
('VOLKSWAGEN','POINTER','ROJO',4);

-- DATOS DE PRUEBA PARA REPARACIONES
INSERT INTO REPARACIONES (COSTO_TOTAL,COSTO_PENDIENTE,DESCRIPCION,FECHA_REPARACION,CON_FACTURA,ID_VEHICULO) VALUES
(350,0,'REPARACION DE MARCHA',NOW(),FALSE,1),
(550,0,'REPARACION DE ALTERNADOR',NOW(),FALSE,1),
(550,0,'REPARACION DE ALTERNADOR',NOW(),TRUE,4),
(50,0,'CAMBIAR FOCO',NOW(),FALSE,3);

-- CONSULTA PRINCIPAL DE PRUEBA
SELECT c.NOMBRE,c.TELEFONO, CONCAT(v.MARCA," ", v.MODELO) as COCHE,
r.COSTO_TOTAL, r.COSTO_PENDIENTE, r.DESCRIPCION AS REPARACION, r.FECHA_REPARACION, r.CON_FACTURA
FROM CLIENTES AS c
LEFT JOIN VEHICULOS AS v ON c.ID_CLIENTE = v.ID_CLIENTE
LEFT JOIN REPARACIONES AS r ON v.ID_VEHICULO = r.ID_VEHICULO WHERE r.ID_REPARACION IS NOT NULL;