-- CREACION DE LA BASE DE DATOS
DROP DATABASE IF EXISTS TALLER;
CREATE DATABASE IF NOT EXISTS TALLER;
USE TALLER;

-- CREACION DE LA TABLA DE CLIENTES
DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(10)
);

-- CREACION DE LA TABLA DE VEHICULOS
DROP TABLE IF EXISTS VEHICULOS;
CREATE TABLE VEHICULOS(
    ID_VEHICULO INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50),
    COLOR VARCHAR(30) NOT NULL,
    ID_CLIENTE INT NOT NULL
);

-- CREACION DE LA TABLA DE REPARACIONES
DROP TABLE IF EXISTS REPARACIONES;
CREATE TABLE REPARACIONES(
    ID_REPARACION INT AUTO_INCREMENT PRIMARY KEY,
    COSTO_TOTAL FLOAT NOT NULL,
    COSTO_PENDIENTE FLOAT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    CON_FACTURA BOOLEAN  NOT NULL DEFAULT FALSE,
    ID_VEHICULO INT NOT NULL
);
